OnlineJobPortalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from portal.forms import UserLoginForm
from portal.views import (
    jobseeker_register,
    employer_register,
    login_request,
    home_page,
    job_detail,
    search,
    filter_by_category,
)



urlpatterns = [
    path('emoloyer/', include('employer.urls')),
    path('user/', include('jobseeker.urls')),
    path('', home_page, name='home-page'),
    path('admin/', admin.site.urls),
    path('register/', jobseeker_register, name='register'),
    path('employer/register/', employer_register, name='employer-register'),
    path('login/', login_request, name='login'),
    path('job/<int:id>/', job_detail, name='job-detail'),
    path('search/', search, name='search'),
    path('filter/category/<category>', filter_by_category, name='filter-by-category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

employer/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (employer_home,
                   employer_profile,
                   employer_jobs,
                   employer_create_job,
                   accepted_status,
                   hired_status,
                   delete_request,
                   )


urlpatterns = [
    path('home', employer_home , name='employer-home'),
    path('profile/', employer_profile , name='employer-profile'),
    path('jobs/', employer_jobs , name='employer-jobs'),
    path('create/job/', employer_create_job , name='employer-create-job'),
    path('accept/request/<int:id>/', accepted_status, name='accept-status'),
    path('hire/request/<int:id>/', hired_status, name='hire-status'),
    path('delete/request/<int:id>/', delete_request, name='delete-request'),
    path('logout/',LogoutView.as_view(), name='logout'),
    
]

employer/models.py
import datetime
import humanize

from PIL import Image
from django.db import models
from django.utils import timezone
from django_jalali.db import models as jmodels

from portal.models import  User, Category


class Company(models.Model):
    employer = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    co_introduction = models.TextField()
    logo = models.ImageField(default='default.png', upload_to='co-logo')
    link  = models.CharField(max_length=80)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super(Company, self).save(*args, **kwargs)

        img = Image.open(self.logo.path)


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='jobs')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    title = models.CharField(max_length=80)
    location = models.CharField(max_length=80)
    created_date = models.DateTimeField(default=datetime.datetime.now(), blank=True)
    experience_choices = (
        ('no-matter','No matter'),
        ('1-3', 'one to 3 years'),
        ('3-6', 'three to 6 years'),
        ('+6', 'more than 6 years'),
    )
    experience = models.CharField(max_length=80, choices=experience_choices)
    salary_choices = (
        ('agreement ', 'consensual'),
        ('from 3', 'from 3 million'),
        ('from 5', 'from 5 million'),
        ('from 8', 'from 8 million'),
        ('from 10', 'from 10 million'),
        ('from 12', 'from 12 million'),
        ('from 15', 'from 15 million'),
    )
    salary = models.CharField(
        max_length=80, choices=salary_choices
    )
    cooperation_choices = (
        ('full-time', 'full-time'),
        ('part-time', 'part-time'),
        ('remote', 'remote'),
        ('internship', 'internship'),
    )
    cooperation_type = models.CharField(
        max_length=80, choices=cooperation_choices
    )
    job_description = models.TextField()
    skills_required = models.CharField(max_length=80)
    military_choices = (
        ('no-matter', 'no-matter'),
        ('end', 'end of service'),
    )
    military_service = models.CharField(
        max_length=80, choices=military_choices
    )
    degree_choices = (
        ('no-matter', 'no-matter'),
        ('diploma', 'diploma'),
        ('bachelor', 'bachelor'),
    )
    degree = models.CharField(max_length=80, choices=degree_choices)
    gender_choices = (
        ('Male', 'men'),
        ('Female', 'women'),
        ('not-matter','not-matter'),
    )
    gender = models.CharField(max_length=10, choices=gender_choices)

    def __str__(self):
        return self.title
    
    
class JobRequests(models.Model):
    employer = models.ForeignKey(Company, on_delete=models.CASCADE)
    jobseeker = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume_url = models.CharField(max_length=100)
    accepted = models.BooleanField(default=False)
    hired = models.BooleanField(default=False)
    viewed = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.jobseeker} requested on {self.job}'
    
    def save(self, *args, **kwargs):
        super(JobRequests, self).save(*args, **kwargs)

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from portal.managers import MyUserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100)
    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_jobseeker = models.BooleanField(default=True)
    
    objects = MyUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Category(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
       return self.name

portal/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(
        label='name and surname',
        widget=forms.TextInput(
           attrs={'placeholder': 'For example: Vasanth',}
           )
        )
    email = forms.EmailField(
        label='email address',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Enter your email address'}
            )
        )
    password1 = forms.CharField(
        label='password',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Enter your password'}
            )
        )
    password2 = forms.CharField(
        label='repeat the password',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Repeat your password'}
            )
        )
    
    error_messages = {
        'password_mismatch': "password not equal",
    }
    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email has already been used")
        return email

    class Meta:
        model = User
        fields=['full_name', 'email', 'password1', 'password2']


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        label='email address',
        widget=forms.EmailInput(
           attrs={'placeholder': 'Enter your email address'}
        )
    )
    password = forms.CharField(
        label='password',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Enter your password'}
        )
    )

portal/views.py
from datetime import datetime, timezone

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.http import Http404

from employer.models import Job
from jobseeker.models import JobSeekerRequests
from .forms import UserRegisterForm, UserLoginForm
from .models import User


def home_page(request):
    jobs = Job.objects.order_by('-created_date').all()
    # convert time
    now = datetime.now(timezone.utc)
    for i in jobs:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} the other day'
    return render(request, 'home_page.html', {'jobs':jobs})


def job_detail(request, id):
    job = get_object_or_404(Job, id=id)
    return render(request, 'job_detail.html', {'job':job})


def employer_register(request):
    if request.user.is_authenticated:
            raise Http404
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                    data['email'],
                    data['full_name'],
                    data['password1'],
            )
            user.is_jobseeker = False
            user.save()
            messages.success(
                request, 'Registration completed - login via the form below'
            )
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'employer/register.html', {'form':form})


def jobseeker_register(request):
    if request.user.is_authenticated:
            raise Http404
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                    data['email'],
                    data['full_name'],
                    data['password1'],
            )
            user.save()
            messages.success(
                request, 'Registration done - login via the form below'
            )
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'jobseeker/register.html', {'form':form})


def login_request(request):
    if request.user.is_authenticated:
        raise Http404
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None:
                login(request, user)
                # if user is jobseeker
                if user.is_jobseeker:
                    return redirect('home-page')
                # if user is a employer
                elif not user.is_jobseeker:
                    return redirect('employer-home')
            else:
                messages.success(request, 'The username and password are not correct')
                return redirect('login')
    form = UserLoginForm()
    return render(request, 'login.html', {'form':form})


def search(request):
    query = request.GET.get('q')
    resaults =  Job.objects.filter(title__icontains=query).all()
    now = datetime.now(timezone.utc)
    for i in resaults:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} days ago'
    return render(request, 'home_page.html', {'jobs':resaults})


def filter_by_category(request, category):
    resaults = Job.objects.filter(category__name=category).all()
    now = datetime.now(timezone.utc)
    for i in resaults:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f'{get_days.days} days ago'
    return render(request, 'home_page.html', {'jobs':resaults})

portal/templates/base.html
{% load static %}
<html dir="rtl" lang="fa">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- my js -->
  
  <!-- Blog CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <!-- google Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Online Job Recruitment Portal</title>
  {% endif %}
</head>
<body>
<!-- Navbar -->
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'home-page' %}">Online Job Recruitment Portal</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <!-- search form -->
                <form class="form-inline my-2 my-lg-0 ml-5" action="{% url 'search' %}">
                  <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
                  <input name="q" data-filter="1" class="form-control mr-sm-1" type="search" aria-label="Search">
                </form>
              </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                {% if not user.is_jobseeker %}
                  {% if user.company.jobs %}
                    <a class="nav-item nav-link" href="{% url 'employer-jobs' %}">My ads</a>
                    <a class="nav-item nav-link" href="{% url 'employer-create-job' %}">New ad</a>
                    <a class="nav-item nav-link" href="{% url 'employer-profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                    <a class="nav-item nav-link" href="{% url 'employer-profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  {% endif %}
                {% endif %}
              {% if user.is_jobseeker %}
                <a class="nav-item nav-link" href="{% url 'saved-jobs' %}">Tagged</a>
                <a class="nav-item nav-link" href="{% url 'jobseeker-requests' %}">My Requests</a>
                <a class="nav-item nav-link" href="{% url 'jobseeker-profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% endif %}
              {% else %}
                <a class="nav-item nav-link" href="{% url 'employer-register' %}">employers section</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Jobseeker Registration</a>
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </div>
          </div>

        </div>
      </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-9">
            <!-- flash messages -->
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-3">
            <div class="content-section">
                <h6>
                  <i class="material-icons ml-1" style="vertical-align: middle;">&#xe3c7;</i>Categories
                </h6>
                {% for category in categories %}
                <li class="list-group-item">
                  <a href="{% url 'filter-by-category' category %}" style="color:grey;">
                    <input type="checkbox" style="vertical-align: middle;">
                    {{ category }}
                  </a>
                </li>
              {% endfor %}
                <h6 class="mt-3">
                  <i class="material-icons mb-1 ml-1" style="vertical-align: middle;font-size: 20px;">&#xe0c8;</i>Province
                </h6>
                {% for category in categories %}
                <li class="list-group-item">
                  <a href="{% url 'filter-by-category' category %}" style="color:grey;">
                    <input type="checkbox" style="vertical-align: middle;">
                    {{ category }}
                  </a>
                </li>
              {% endfor %}
              <h6 class="mt-3">
                <i class="material-icons mb-1 ml-1" style="vertical-align: middle;font-size: 20px;">&#xe8f9;</i>put type
              </h6>
              {% for category in categories %}
              <li class="list-group-item">
                <a href="{% url 'filter-by-category' category %}" style="color:grey;">
                  <input type="checkbox" style="vertical-align: middle;">
                  {{ category }}
                </a>
              </li>
            {% endfor %}
            <h6 class="mt-3">
              <i class="material-icons mb-1 ml-1" style="vertical-align: middle;font-size: 20px;">&#xe416;</i>Work history
            </h6>
            {% for category in categories %}
            <li class="list-group-item">
              <a href="{% url 'filter-by-category' category %}" style="color:grey;">
                <input type="checkbox" style="vertical-align: middle;">{{ category }}
              </a>
            </li>
          {% endfor %}
          <h6 class="mt-3">
            <i class="material-icons mb-1 ml-1" style="vertical-align: middle;font-size: 20px;">&#xe227;</i>Minimum salary
          </h6>
          {% for category in categories %}
          <li class="list-group-item">
            <a href="{% url 'filter-by-category' category %}" style="color:grey;">
              <input type="checkbox" style="vertical-align: middle;">{{ category }}
            </a>
          </li>
        {% endfor %}
            </div>
          </div>
        </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

portal/templates/home_page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="content-section">
  <legend class="mb-4">Latest job opportunities</legend>
  {% for job in jobs %}
  <article class="media content-section">
    <img class="account-img" src="{{ job.company.logo.url }}">
    <div style="width: 100%;">
      <span><a class="article-title" href="{% url 'job-detail' job.id %}">{{ job.title }}</a></span>
      <span class="text-muted mr-1" style="font-size: small;" >
        {% if job.created_date|naturalday == 'today' %}
        <td>(Today)</td>
        {% elif job.created_date|naturalday == 'yesterday' %}
        <td>(yesterday)</td>
        {% else %}
        <td >({{ job.created_date|naturaltime }})</td>
        {% endif %}
      </span><br>
      <i class="material-icons" style="vertical-align: middle;font-size: medium;">&#xe88a;</i>
      <span style="vertical-align:middle;font-size:small;">{{ job.company }}</span><br>
      <i class="material-icons" style="vertical-align: middle;font-size: medium;">&#xe0c8;</i> 
      <span style="vertical-align:middle;font-size:small;">{{ job.location }} </span><br>
      <i class="material-icons" style="vertical-align: middle;font-size: medium;" >&#xe8f9;</i>
      <span style="vertical-align:middle;font-size:small;">{{ job.get_cooperation_type_display }}</span>
      <span  class="text-muted" style="font-size: small;vertical-align: middle;">(Rights {{ job.get_salary_display }})</span>
      <br>
    </div>
    <div style="float: left;text-align: center;margin-top: 16px;vertical-align: middle;">
      <a class="btn btn-outline-info" style="font-size: 12px;" href="{% url 'save-job' job.id %}">
        <i class="material-icons" style="font-size: 20px;vertical-align: middle;font-size:18px;">&#xe83a;</i>show
      </a><br>
      <a style="margin-top: 5px;" class="btn btn-info" href="{% url 'request-job' job.id %}">Send resume</a>
    </div>
  </article>
{% endfor %}
</div>
{% endblock %}

portal/templates/job_detail.html
{% extends "base.html" %}
{% block content %}

<article class="media content-section">
  <div class="media-body">
    <img class="account-img" src="{{ job.company.logo.url }}">
    <a style="font-size: 30px;"> company {{ job.company }}</a>
    <small class="text-muted"><a href="{{ job.company.link }}">(website)</a></small>
    <div class="article-metadata mt-2">
      </div>
      <h3 class="article-title mt-3">{{ job.title }}</h3  >
      <hr>
      Location:
      <span class="job-property ml-5">
        {{ job.location }}
      </span>
      Grouping : 
      <span class="job-property" >
        {{ job.category }}
      </span><br><br>
      work experience:
      <span class="job-property ml-5" >
        {{ job.get_experience_display }}
      </span>
      Rights:
      <span class="job-property ml-5" >
      {{ job.get_salary_display }}
      </span>
      cooperation:
      <span class="job-property" >
      {{ job.get_cooperation_type_display }}
    </span>
    <legend class="mt-5 mb-3" >Job Description  </legend>
      <p class="article-content">{{ job.job_description }}</p>
    <legend class="mt-5 mb-3">Company introduction</legend>
      <p class="mb-5">{{job.company.co_introduction}}</p>
    <p>
      Required skills:
    </p>
    <span class="job-property ml-5">
        {{ job.skills_required }}
    </span>
    <br>
    <br>
    military service status:
    <span class="job-property ml-5">
      {{ job.get_military_service_display }}
    </span>
    education:
    <span class="job-property ml-5">
      {{ job.get_degree_display }}
    </span>
    Gender:
    <span class="job-property ">
      {{ job.get_gender_display }}
    </span>
  </div>      
</article>

{% endblock %}

portal/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" style="width:100%;" type="submit">login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="btn btn-outline-info" href="{% url 'employer-register' %}">employer register</a>
                <a class="btn btn-outline-info" href="{% url 'register' %}">Jobseeker Registration</a>
            </small>
        </div>
    </div>
{% endblock %}